### ISSUE TITLE
test.py gives error: "AttributeError: 'Sensirion' object has no attribute '_start_measurement'"

### ISSUE THREAD

**Issue by schweini** [FEEprojects/sensirion-sps030#7]
Running test.py does seem to output some data, but crashes with:

```
  File "test.py", line 11, in <module>
    SPS030._start_measurement()
AttributeError: 'Sensirion' object has no attribute '_start_measurement'

```

**Comment by FlorentinBulotAQ** [comment]
Thanks a lot for spotting this error.

I have changed test.py to run correctly. If your device is plugged on `/dev/ttyUSB0`, then you should run `python3 test.py /dev/ttyUSB0` to obtain a measurement.

Let me know if you have any additional issue with the library.
